replicaCount: 2

image:
  repository: rickmorty-app
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

cache:
  ttl: 60

ingress:
  enabled: true
  host: rickmorty.local

secrets:
  db_url: "postgresql://postgres:password1234@db:5432/rickmorty_db"
