version: "3.9"

services:
  db:
    image: postgres:15
    container_name: rickmorty-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rickmorty_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rickmorty-app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/rickmorty_db
    ports:
      - "8000:8000"

volumes:
  pgdata: